-- Review before applying to mocadb_private_tables.
-- Generated by scripts/stage_cpapir_omm_bandpasses.py.
-- Source: https://www.omm-astro.ca/en/for-observers/instruments-guide/
-- OMM provides CPAPIR filter centers and widths, not measured transmission curves.
-- Bandpass rows below are rectangular approximations over lambda +/- Delta_lambda/2.
-- min_wavelength/max_wavelength are the 5%/95% CDF points of that rectangular approximation.
-- Zeropoints are intentionally left unchanged.
-- OMM also lists Pa beta and H2, but no matching CPAPIR moca_psid currently exists.
-- cpapir_kmag is mapped to the OMM Ks entry.

-- cpapir_jmag: J, lambda=1.25 um, Delta_lambda=0.16 um
SELECT
  'cpapir_jmag' AS `moca_psid`,
  ps.`average_wavelength` AS `current_average_wavelength`,
  12500 AS `proposed_average_wavelength`,
  ps.`min_wavelength` AS `current_min_wavelength`,
  11780 AS `proposed_min_wavelength`,
  ps.`max_wavelength` AS `current_max_wavelength`,
  13220 AS `proposed_max_wavelength`,
  ps.`zeropoint_jansky` AS `current_zeropoint_jansky`
FROM `moca_photometry_systems` ps
WHERE ps.`moca_psid` = 'cpapir_jmag';

UPDATE `moca_photometry_systems`
SET
  `average_wavelength` = COALESCE(`average_wavelength`, 12500),
  `min_wavelength` = COALESCE(`min_wavelength`, 11780),
  `max_wavelength` = COALESCE(`max_wavelength`, 13220),
  `bandpass_file` = COALESCE(`bandpass_file`, 'OMM CPAPIR rectangular approximation J; https://www.omm-astro.ca/en/for-observers/instruments-guide/')
WHERE `moca_psid` = 'cpapir_jmag';

CREATE TEMPORARY TABLE IF NOT EXISTS `_mocaviz_cpapir_bandpass_stage` (
  `moca_psid` varchar(128) NOT NULL,
  `wavelength_angstrom` double NOT NULL,
  `relative_spectral_response` double NOT NULL
) ENGINE=Memory;
DELETE FROM `_mocaviz_cpapir_bandpass_stage`;
INSERT INTO `_mocaviz_cpapir_bandpass_stage`
  (`moca_psid`, `wavelength_angstrom`, `relative_spectral_response`)
VALUES
  ('cpapir_jmag', 11700, 1),
  ('cpapir_jmag', 11716, 1),
  ('cpapir_jmag', 11732, 1),
  ('cpapir_jmag', 11748, 1),
  ('cpapir_jmag', 11764, 1),
  ('cpapir_jmag', 11780, 1),
  ('cpapir_jmag', 11796, 1),
  ('cpapir_jmag', 11812, 1),
  ('cpapir_jmag', 11828, 1),
  ('cpapir_jmag', 11844, 1),
  ('cpapir_jmag', 11860, 1),
  ('cpapir_jmag', 11876, 1),
  ('cpapir_jmag', 11892, 1),
  ('cpapir_jmag', 11908, 1),
  ('cpapir_jmag', 11924, 1),
  ('cpapir_jmag', 11940, 1),
  ('cpapir_jmag', 11956, 1),
  ('cpapir_jmag', 11972, 1),
  ('cpapir_jmag', 11988, 1),
  ('cpapir_jmag', 12004, 1),
  ('cpapir_jmag', 12020, 1),
  ('cpapir_jmag', 12036, 1),
  ('cpapir_jmag', 12052, 1),
  ('cpapir_jmag', 12068, 1),
  ('cpapir_jmag', 12084, 1),
  ('cpapir_jmag', 12100, 1),
  ('cpapir_jmag', 12116, 1),
  ('cpapir_jmag', 12132, 1),
  ('cpapir_jmag', 12148, 1),
  ('cpapir_jmag', 12164, 1),
  ('cpapir_jmag', 12180, 1),
  ('cpapir_jmag', 12196, 1),
  ('cpapir_jmag', 12212, 1),
  ('cpapir_jmag', 12228, 1),
  ('cpapir_jmag', 12244, 1),
  ('cpapir_jmag', 12260, 1),
  ('cpapir_jmag', 12276, 1),
  ('cpapir_jmag', 12292, 1),
  ('cpapir_jmag', 12308, 1),
  ('cpapir_jmag', 12324, 1),
  ('cpapir_jmag', 12340, 1),
  ('cpapir_jmag', 12356, 1),
  ('cpapir_jmag', 12372, 1),
  ('cpapir_jmag', 12388, 1),
  ('cpapir_jmag', 12404, 1),
  ('cpapir_jmag', 12420, 1),
  ('cpapir_jmag', 12436, 1),
  ('cpapir_jmag', 12452, 1),
  ('cpapir_jmag', 12468, 1),
  ('cpapir_jmag', 12484, 1),
  ('cpapir_jmag', 12500, 1),
  ('cpapir_jmag', 12516, 1),
  ('cpapir_jmag', 12532, 1),
  ('cpapir_jmag', 12548, 1),
  ('cpapir_jmag', 12564, 1),
  ('cpapir_jmag', 12580, 1),
  ('cpapir_jmag', 12596, 1),
  ('cpapir_jmag', 12612, 1),
  ('cpapir_jmag', 12628, 1),
  ('cpapir_jmag', 12644, 1),
  ('cpapir_jmag', 12660, 1),
  ('cpapir_jmag', 12676, 1),
  ('cpapir_jmag', 12692, 1),
  ('cpapir_jmag', 12708, 1),
  ('cpapir_jmag', 12724, 1),
  ('cpapir_jmag', 12740, 1),
  ('cpapir_jmag', 12756, 1),
  ('cpapir_jmag', 12772, 1),
  ('cpapir_jmag', 12788, 1),
  ('cpapir_jmag', 12804, 1),
  ('cpapir_jmag', 12820, 1),
  ('cpapir_jmag', 12836, 1),
  ('cpapir_jmag', 12852, 1),
  ('cpapir_jmag', 12868, 1),
  ('cpapir_jmag', 12884, 1),
  ('cpapir_jmag', 12900, 1),
  ('cpapir_jmag', 12916, 1),
  ('cpapir_jmag', 12932, 1),
  ('cpapir_jmag', 12948, 1),
  ('cpapir_jmag', 12964, 1),
  ('cpapir_jmag', 12980, 1),
  ('cpapir_jmag', 12996, 1),
  ('cpapir_jmag', 13012, 1),
  ('cpapir_jmag', 13028, 1),
  ('cpapir_jmag', 13044, 1),
  ('cpapir_jmag', 13060, 1),
  ('cpapir_jmag', 13076, 1),
  ('cpapir_jmag', 13092, 1),
  ('cpapir_jmag', 13108, 1),
  ('cpapir_jmag', 13124, 1),
  ('cpapir_jmag', 13140, 1),
  ('cpapir_jmag', 13156, 1),
  ('cpapir_jmag', 13172, 1),
  ('cpapir_jmag', 13188, 1),
  ('cpapir_jmag', 13204, 1),
  ('cpapir_jmag', 13220, 1),
  ('cpapir_jmag', 13236, 1),
  ('cpapir_jmag', 13252, 1),
  ('cpapir_jmag', 13268, 1),
  ('cpapir_jmag', 13284, 1),
  ('cpapir_jmag', 13300, 1);
INSERT INTO `data_photometric_bandpasses`
  (`moca_psid`, `wavelength_angstrom`, `relative_spectral_response`)
SELECT
  stage.`moca_psid`,
  stage.`wavelength_angstrom`,
  stage.`relative_spectral_response`
FROM `_mocaviz_cpapir_bandpass_stage` stage
WHERE NOT EXISTS (
  SELECT 1
  FROM `data_photometric_bandpasses` existing
  WHERE existing.`moca_psid` = 'cpapir_jmag'
  LIMIT 1
)
ORDER BY stage.`wavelength_angstrom`;
DELETE FROM `_mocaviz_cpapir_bandpass_stage`;

-- cpapir_ch4mag: CH4, lambda=1.57 um, Delta_lambda=0.05 um
SELECT
  'cpapir_ch4mag' AS `moca_psid`,
  ps.`average_wavelength` AS `current_average_wavelength`,
  15700 AS `proposed_average_wavelength`,
  ps.`min_wavelength` AS `current_min_wavelength`,
  15475 AS `proposed_min_wavelength`,
  ps.`max_wavelength` AS `current_max_wavelength`,
  15925 AS `proposed_max_wavelength`,
  ps.`zeropoint_jansky` AS `current_zeropoint_jansky`
FROM `moca_photometry_systems` ps
WHERE ps.`moca_psid` = 'cpapir_ch4mag';

UPDATE `moca_photometry_systems`
SET
  `average_wavelength` = COALESCE(`average_wavelength`, 15700),
  `min_wavelength` = COALESCE(`min_wavelength`, 15475),
  `max_wavelength` = COALESCE(`max_wavelength`, 15925),
  `bandpass_file` = COALESCE(`bandpass_file`, 'OMM CPAPIR rectangular approximation CH4; https://www.omm-astro.ca/en/for-observers/instruments-guide/')
WHERE `moca_psid` = 'cpapir_ch4mag';

CREATE TEMPORARY TABLE IF NOT EXISTS `_mocaviz_cpapir_bandpass_stage` (
  `moca_psid` varchar(128) NOT NULL,
  `wavelength_angstrom` double NOT NULL,
  `relative_spectral_response` double NOT NULL
) ENGINE=Memory;
DELETE FROM `_mocaviz_cpapir_bandpass_stage`;
INSERT INTO `_mocaviz_cpapir_bandpass_stage`
  (`moca_psid`, `wavelength_angstrom`, `relative_spectral_response`)
VALUES
  ('cpapir_ch4mag', 15450, 1),
  ('cpapir_ch4mag', 15455, 1),
  ('cpapir_ch4mag', 15460, 1),
  ('cpapir_ch4mag', 15465, 1),
  ('cpapir_ch4mag', 15470, 1),
  ('cpapir_ch4mag', 15475, 1),
  ('cpapir_ch4mag', 15480, 1),
  ('cpapir_ch4mag', 15485, 1),
  ('cpapir_ch4mag', 15490, 1),
  ('cpapir_ch4mag', 15495, 1),
  ('cpapir_ch4mag', 15500, 1),
  ('cpapir_ch4mag', 15505, 1),
  ('cpapir_ch4mag', 15510, 1),
  ('cpapir_ch4mag', 15515, 1),
  ('cpapir_ch4mag', 15520, 1),
  ('cpapir_ch4mag', 15525, 1),
  ('cpapir_ch4mag', 15530, 1),
  ('cpapir_ch4mag', 15535, 1),
  ('cpapir_ch4mag', 15540, 1),
  ('cpapir_ch4mag', 15545, 1),
  ('cpapir_ch4mag', 15550, 1),
  ('cpapir_ch4mag', 15555, 1),
  ('cpapir_ch4mag', 15560, 1),
  ('cpapir_ch4mag', 15565, 1),
  ('cpapir_ch4mag', 15570, 1),
  ('cpapir_ch4mag', 15575, 1),
  ('cpapir_ch4mag', 15580, 1),
  ('cpapir_ch4mag', 15585, 1),
  ('cpapir_ch4mag', 15590, 1),
  ('cpapir_ch4mag', 15595, 1),
  ('cpapir_ch4mag', 15600, 1),
  ('cpapir_ch4mag', 15605, 1),
  ('cpapir_ch4mag', 15610, 1),
  ('cpapir_ch4mag', 15615, 1),
  ('cpapir_ch4mag', 15620, 1),
  ('cpapir_ch4mag', 15625, 1),
  ('cpapir_ch4mag', 15630, 1),
  ('cpapir_ch4mag', 15635, 1),
  ('cpapir_ch4mag', 15640, 1),
  ('cpapir_ch4mag', 15645, 1),
  ('cpapir_ch4mag', 15650, 1),
  ('cpapir_ch4mag', 15655, 1),
  ('cpapir_ch4mag', 15660, 1),
  ('cpapir_ch4mag', 15665, 1),
  ('cpapir_ch4mag', 15670, 1),
  ('cpapir_ch4mag', 15675, 1),
  ('cpapir_ch4mag', 15680, 1),
  ('cpapir_ch4mag', 15685, 1),
  ('cpapir_ch4mag', 15690, 1),
  ('cpapir_ch4mag', 15695, 1),
  ('cpapir_ch4mag', 15700, 1),
  ('cpapir_ch4mag', 15705, 1),
  ('cpapir_ch4mag', 15710, 1),
  ('cpapir_ch4mag', 15715, 1),
  ('cpapir_ch4mag', 15720, 1),
  ('cpapir_ch4mag', 15725, 1),
  ('cpapir_ch4mag', 15730, 1),
  ('cpapir_ch4mag', 15735, 1),
  ('cpapir_ch4mag', 15740, 1),
  ('cpapir_ch4mag', 15745, 1),
  ('cpapir_ch4mag', 15750, 1),
  ('cpapir_ch4mag', 15755, 1),
  ('cpapir_ch4mag', 15760, 1),
  ('cpapir_ch4mag', 15765, 1),
  ('cpapir_ch4mag', 15770, 1),
  ('cpapir_ch4mag', 15775, 1),
  ('cpapir_ch4mag', 15780, 1),
  ('cpapir_ch4mag', 15785, 1),
  ('cpapir_ch4mag', 15790, 1),
  ('cpapir_ch4mag', 15795, 1),
  ('cpapir_ch4mag', 15800, 1),
  ('cpapir_ch4mag', 15805, 1),
  ('cpapir_ch4mag', 15810, 1),
  ('cpapir_ch4mag', 15815, 1),
  ('cpapir_ch4mag', 15820, 1),
  ('cpapir_ch4mag', 15825, 1),
  ('cpapir_ch4mag', 15830, 1),
  ('cpapir_ch4mag', 15835, 1),
  ('cpapir_ch4mag', 15840, 1),
  ('cpapir_ch4mag', 15845, 1),
  ('cpapir_ch4mag', 15850, 1),
  ('cpapir_ch4mag', 15855, 1),
  ('cpapir_ch4mag', 15860, 1),
  ('cpapir_ch4mag', 15865, 1),
  ('cpapir_ch4mag', 15870, 1),
  ('cpapir_ch4mag', 15875, 1),
  ('cpapir_ch4mag', 15880, 1),
  ('cpapir_ch4mag', 15885, 1),
  ('cpapir_ch4mag', 15890, 1),
  ('cpapir_ch4mag', 15895, 1),
  ('cpapir_ch4mag', 15900, 1),
  ('cpapir_ch4mag', 15905, 1),
  ('cpapir_ch4mag', 15910, 1),
  ('cpapir_ch4mag', 15915, 1),
  ('cpapir_ch4mag', 15920, 1),
  ('cpapir_ch4mag', 15925, 1),
  ('cpapir_ch4mag', 15930, 1),
  ('cpapir_ch4mag', 15935, 1),
  ('cpapir_ch4mag', 15940, 1),
  ('cpapir_ch4mag', 15945, 1),
  ('cpapir_ch4mag', 15950, 1);
INSERT INTO `data_photometric_bandpasses`
  (`moca_psid`, `wavelength_angstrom`, `relative_spectral_response`)
SELECT
  stage.`moca_psid`,
  stage.`wavelength_angstrom`,
  stage.`relative_spectral_response`
FROM `_mocaviz_cpapir_bandpass_stage` stage
WHERE NOT EXISTS (
  SELECT 1
  FROM `data_photometric_bandpasses` existing
  WHERE existing.`moca_psid` = 'cpapir_ch4mag'
  LIMIT 1
)
ORDER BY stage.`wavelength_angstrom`;
DELETE FROM `_mocaviz_cpapir_bandpass_stage`;

-- cpapir_hmag: H, lambda=1.65 um, Delta_lambda=0.3 um
SELECT
  'cpapir_hmag' AS `moca_psid`,
  ps.`average_wavelength` AS `current_average_wavelength`,
  16500 AS `proposed_average_wavelength`,
  ps.`min_wavelength` AS `current_min_wavelength`,
  15150 AS `proposed_min_wavelength`,
  ps.`max_wavelength` AS `current_max_wavelength`,
  17850 AS `proposed_max_wavelength`,
  ps.`zeropoint_jansky` AS `current_zeropoint_jansky`
FROM `moca_photometry_systems` ps
WHERE ps.`moca_psid` = 'cpapir_hmag';

UPDATE `moca_photometry_systems`
SET
  `average_wavelength` = COALESCE(`average_wavelength`, 16500),
  `min_wavelength` = COALESCE(`min_wavelength`, 15150),
  `max_wavelength` = COALESCE(`max_wavelength`, 17850),
  `bandpass_file` = COALESCE(`bandpass_file`, 'OMM CPAPIR rectangular approximation H; https://www.omm-astro.ca/en/for-observers/instruments-guide/')
WHERE `moca_psid` = 'cpapir_hmag';

CREATE TEMPORARY TABLE IF NOT EXISTS `_mocaviz_cpapir_bandpass_stage` (
  `moca_psid` varchar(128) NOT NULL,
  `wavelength_angstrom` double NOT NULL,
  `relative_spectral_response` double NOT NULL
) ENGINE=Memory;
DELETE FROM `_mocaviz_cpapir_bandpass_stage`;
INSERT INTO `_mocaviz_cpapir_bandpass_stage`
  (`moca_psid`, `wavelength_angstrom`, `relative_spectral_response`)
VALUES
  ('cpapir_hmag', 15000, 1),
  ('cpapir_hmag', 15030, 1),
  ('cpapir_hmag', 15060, 1),
  ('cpapir_hmag', 15090, 1),
  ('cpapir_hmag', 15120, 1),
  ('cpapir_hmag', 15150, 1),
  ('cpapir_hmag', 15180, 1),
  ('cpapir_hmag', 15210, 1),
  ('cpapir_hmag', 15240, 1),
  ('cpapir_hmag', 15270, 1),
  ('cpapir_hmag', 15300, 1),
  ('cpapir_hmag', 15330, 1),
  ('cpapir_hmag', 15360, 1),
  ('cpapir_hmag', 15390, 1),
  ('cpapir_hmag', 15420, 1),
  ('cpapir_hmag', 15450, 1),
  ('cpapir_hmag', 15480, 1),
  ('cpapir_hmag', 15510, 1),
  ('cpapir_hmag', 15540, 1),
  ('cpapir_hmag', 15570, 1),
  ('cpapir_hmag', 15600, 1),
  ('cpapir_hmag', 15630, 1),
  ('cpapir_hmag', 15660, 1),
  ('cpapir_hmag', 15690, 1),
  ('cpapir_hmag', 15720, 1),
  ('cpapir_hmag', 15750, 1),
  ('cpapir_hmag', 15780, 1),
  ('cpapir_hmag', 15810, 1),
  ('cpapir_hmag', 15840, 1),
  ('cpapir_hmag', 15870, 1),
  ('cpapir_hmag', 15900, 1),
  ('cpapir_hmag', 15930, 1),
  ('cpapir_hmag', 15960, 1),
  ('cpapir_hmag', 15990, 1),
  ('cpapir_hmag', 16020, 1),
  ('cpapir_hmag', 16050, 1),
  ('cpapir_hmag', 16080, 1),
  ('cpapir_hmag', 16110, 1),
  ('cpapir_hmag', 16140, 1),
  ('cpapir_hmag', 16170, 1),
  ('cpapir_hmag', 16200, 1),
  ('cpapir_hmag', 16230, 1),
  ('cpapir_hmag', 16260, 1),
  ('cpapir_hmag', 16290, 1),
  ('cpapir_hmag', 16320, 1),
  ('cpapir_hmag', 16350, 1),
  ('cpapir_hmag', 16380, 1),
  ('cpapir_hmag', 16410, 1),
  ('cpapir_hmag', 16440, 1),
  ('cpapir_hmag', 16470, 1),
  ('cpapir_hmag', 16500, 1),
  ('cpapir_hmag', 16530, 1),
  ('cpapir_hmag', 16560, 1),
  ('cpapir_hmag', 16590, 1),
  ('cpapir_hmag', 16620, 1),
  ('cpapir_hmag', 16650, 1),
  ('cpapir_hmag', 16680, 1),
  ('cpapir_hmag', 16710, 1),
  ('cpapir_hmag', 16740, 1),
  ('cpapir_hmag', 16770, 1),
  ('cpapir_hmag', 16800, 1),
  ('cpapir_hmag', 16830, 1),
  ('cpapir_hmag', 16860, 1),
  ('cpapir_hmag', 16890, 1),
  ('cpapir_hmag', 16920, 1),
  ('cpapir_hmag', 16950, 1),
  ('cpapir_hmag', 16980, 1),
  ('cpapir_hmag', 17010, 1),
  ('cpapir_hmag', 17040, 1),
  ('cpapir_hmag', 17070, 1),
  ('cpapir_hmag', 17100, 1),
  ('cpapir_hmag', 17130, 1),
  ('cpapir_hmag', 17160, 1),
  ('cpapir_hmag', 17190, 1),
  ('cpapir_hmag', 17220, 1),
  ('cpapir_hmag', 17250, 1),
  ('cpapir_hmag', 17280, 1),
  ('cpapir_hmag', 17310, 1),
  ('cpapir_hmag', 17340, 1),
  ('cpapir_hmag', 17370, 1),
  ('cpapir_hmag', 17400, 1),
  ('cpapir_hmag', 17430, 1),
  ('cpapir_hmag', 17460, 1),
  ('cpapir_hmag', 17490, 1),
  ('cpapir_hmag', 17520, 1),
  ('cpapir_hmag', 17550, 1),
  ('cpapir_hmag', 17580, 1),
  ('cpapir_hmag', 17610, 1),
  ('cpapir_hmag', 17640, 1),
  ('cpapir_hmag', 17670, 1),
  ('cpapir_hmag', 17700, 1),
  ('cpapir_hmag', 17730, 1),
  ('cpapir_hmag', 17760, 1),
  ('cpapir_hmag', 17790, 1),
  ('cpapir_hmag', 17820, 1),
  ('cpapir_hmag', 17850, 1),
  ('cpapir_hmag', 17880, 1),
  ('cpapir_hmag', 17910, 1),
  ('cpapir_hmag', 17940, 1),
  ('cpapir_hmag', 17970, 1),
  ('cpapir_hmag', 18000, 1);
INSERT INTO `data_photometric_bandpasses`
  (`moca_psid`, `wavelength_angstrom`, `relative_spectral_response`)
SELECT
  stage.`moca_psid`,
  stage.`wavelength_angstrom`,
  stage.`relative_spectral_response`
FROM `_mocaviz_cpapir_bandpass_stage` stage
WHERE NOT EXISTS (
  SELECT 1
  FROM `data_photometric_bandpasses` existing
  WHERE existing.`moca_psid` = 'cpapir_hmag'
  LIMIT 1
)
ORDER BY stage.`wavelength_angstrom`;
DELETE FROM `_mocaviz_cpapir_bandpass_stage`;

-- cpapir_cont2mag: CONT2, lambda=2.033 um, Delta_lambda=0.025 um
SELECT
  'cpapir_cont2mag' AS `moca_psid`,
  ps.`average_wavelength` AS `current_average_wavelength`,
  20330 AS `proposed_average_wavelength`,
  ps.`min_wavelength` AS `current_min_wavelength`,
  20217.5 AS `proposed_min_wavelength`,
  ps.`max_wavelength` AS `current_max_wavelength`,
  20442.5 AS `proposed_max_wavelength`,
  ps.`zeropoint_jansky` AS `current_zeropoint_jansky`
FROM `moca_photometry_systems` ps
WHERE ps.`moca_psid` = 'cpapir_cont2mag';

UPDATE `moca_photometry_systems`
SET
  `average_wavelength` = COALESCE(`average_wavelength`, 20330),
  `min_wavelength` = COALESCE(`min_wavelength`, 20217.5),
  `max_wavelength` = COALESCE(`max_wavelength`, 20442.5),
  `bandpass_file` = COALESCE(`bandpass_file`, 'OMM CPAPIR rectangular approximation CONT2; https://www.omm-astro.ca/en/for-observers/instruments-guide/')
WHERE `moca_psid` = 'cpapir_cont2mag';

CREATE TEMPORARY TABLE IF NOT EXISTS `_mocaviz_cpapir_bandpass_stage` (
  `moca_psid` varchar(128) NOT NULL,
  `wavelength_angstrom` double NOT NULL,
  `relative_spectral_response` double NOT NULL
) ENGINE=Memory;
DELETE FROM `_mocaviz_cpapir_bandpass_stage`;
INSERT INTO `_mocaviz_cpapir_bandpass_stage`
  (`moca_psid`, `wavelength_angstrom`, `relative_spectral_response`)
VALUES
  ('cpapir_cont2mag', 20205, 1),
  ('cpapir_cont2mag', 20207.5, 1),
  ('cpapir_cont2mag', 20210, 1),
  ('cpapir_cont2mag', 20212.5, 1),
  ('cpapir_cont2mag', 20215, 1),
  ('cpapir_cont2mag', 20217.5, 1),
  ('cpapir_cont2mag', 20220, 1),
  ('cpapir_cont2mag', 20222.5, 1),
  ('cpapir_cont2mag', 20225, 1),
  ('cpapir_cont2mag', 20227.5, 1),
  ('cpapir_cont2mag', 20230, 1),
  ('cpapir_cont2mag', 20232.5, 1),
  ('cpapir_cont2mag', 20235, 1),
  ('cpapir_cont2mag', 20237.5, 1),
  ('cpapir_cont2mag', 20240, 1),
  ('cpapir_cont2mag', 20242.5, 1),
  ('cpapir_cont2mag', 20245, 1),
  ('cpapir_cont2mag', 20247.5, 1),
  ('cpapir_cont2mag', 20250, 1),
  ('cpapir_cont2mag', 20252.5, 1),
  ('cpapir_cont2mag', 20255, 1),
  ('cpapir_cont2mag', 20257.5, 1),
  ('cpapir_cont2mag', 20260, 1),
  ('cpapir_cont2mag', 20262.5, 1),
  ('cpapir_cont2mag', 20265, 1),
  ('cpapir_cont2mag', 20267.5, 1),
  ('cpapir_cont2mag', 20270, 1),
  ('cpapir_cont2mag', 20272.5, 1),
  ('cpapir_cont2mag', 20275, 1),
  ('cpapir_cont2mag', 20277.5, 1),
  ('cpapir_cont2mag', 20280, 1),
  ('cpapir_cont2mag', 20282.5, 1),
  ('cpapir_cont2mag', 20285, 1),
  ('cpapir_cont2mag', 20287.5, 1),
  ('cpapir_cont2mag', 20290, 1),
  ('cpapir_cont2mag', 20292.5, 1),
  ('cpapir_cont2mag', 20295, 1),
  ('cpapir_cont2mag', 20297.5, 1),
  ('cpapir_cont2mag', 20300, 1),
  ('cpapir_cont2mag', 20302.5, 1),
  ('cpapir_cont2mag', 20305, 1),
  ('cpapir_cont2mag', 20307.5, 1),
  ('cpapir_cont2mag', 20310, 1),
  ('cpapir_cont2mag', 20312.5, 1),
  ('cpapir_cont2mag', 20315, 1),
  ('cpapir_cont2mag', 20317.5, 1),
  ('cpapir_cont2mag', 20320, 1),
  ('cpapir_cont2mag', 20322.5, 1),
  ('cpapir_cont2mag', 20325, 1),
  ('cpapir_cont2mag', 20327.5, 1),
  ('cpapir_cont2mag', 20330, 1),
  ('cpapir_cont2mag', 20332.5, 1),
  ('cpapir_cont2mag', 20335, 1),
  ('cpapir_cont2mag', 20337.5, 1),
  ('cpapir_cont2mag', 20340, 1),
  ('cpapir_cont2mag', 20342.5, 1),
  ('cpapir_cont2mag', 20345, 1),
  ('cpapir_cont2mag', 20347.5, 1),
  ('cpapir_cont2mag', 20350, 1),
  ('cpapir_cont2mag', 20352.5, 1),
  ('cpapir_cont2mag', 20355, 1),
  ('cpapir_cont2mag', 20357.5, 1),
  ('cpapir_cont2mag', 20360, 1),
  ('cpapir_cont2mag', 20362.5, 1),
  ('cpapir_cont2mag', 20365, 1),
  ('cpapir_cont2mag', 20367.5, 1),
  ('cpapir_cont2mag', 20370, 1),
  ('cpapir_cont2mag', 20372.5, 1),
  ('cpapir_cont2mag', 20375, 1),
  ('cpapir_cont2mag', 20377.5, 1),
  ('cpapir_cont2mag', 20380, 1),
  ('cpapir_cont2mag', 20382.5, 1),
  ('cpapir_cont2mag', 20385, 1),
  ('cpapir_cont2mag', 20387.5, 1),
  ('cpapir_cont2mag', 20390, 1),
  ('cpapir_cont2mag', 20392.5, 1),
  ('cpapir_cont2mag', 20395, 1),
  ('cpapir_cont2mag', 20397.5, 1),
  ('cpapir_cont2mag', 20400, 1),
  ('cpapir_cont2mag', 20402.5, 1),
  ('cpapir_cont2mag', 20405, 1),
  ('cpapir_cont2mag', 20407.5, 1),
  ('cpapir_cont2mag', 20410, 1),
  ('cpapir_cont2mag', 20412.5, 1),
  ('cpapir_cont2mag', 20415, 1),
  ('cpapir_cont2mag', 20417.5, 1),
  ('cpapir_cont2mag', 20420, 1),
  ('cpapir_cont2mag', 20422.5, 1),
  ('cpapir_cont2mag', 20425, 1),
  ('cpapir_cont2mag', 20427.5, 1),
  ('cpapir_cont2mag', 20430, 1),
  ('cpapir_cont2mag', 20432.5, 1),
  ('cpapir_cont2mag', 20435, 1),
  ('cpapir_cont2mag', 20437.5, 1),
  ('cpapir_cont2mag', 20440, 1),
  ('cpapir_cont2mag', 20442.5, 1),
  ('cpapir_cont2mag', 20445, 1),
  ('cpapir_cont2mag', 20447.5, 1),
  ('cpapir_cont2mag', 20450, 1),
  ('cpapir_cont2mag', 20452.5, 1),
  ('cpapir_cont2mag', 20455, 1);
INSERT INTO `data_photometric_bandpasses`
  (`moca_psid`, `wavelength_angstrom`, `relative_spectral_response`)
SELECT
  stage.`moca_psid`,
  stage.`wavelength_angstrom`,
  stage.`relative_spectral_response`
FROM `_mocaviz_cpapir_bandpass_stage` stage
WHERE NOT EXISTS (
  SELECT 1
  FROM `data_photometric_bandpasses` existing
  WHERE existing.`moca_psid` = 'cpapir_cont2mag'
  LIMIT 1
)
ORDER BY stage.`wavelength_angstrom`;
DELETE FROM `_mocaviz_cpapir_bandpass_stage`;

-- cpapir_heimag: HeI, lambda=2.062 um, Delta_lambda=0.015 um
SELECT
  'cpapir_heimag' AS `moca_psid`,
  ps.`average_wavelength` AS `current_average_wavelength`,
  20620 AS `proposed_average_wavelength`,
  ps.`min_wavelength` AS `current_min_wavelength`,
  20552.5 AS `proposed_min_wavelength`,
  ps.`max_wavelength` AS `current_max_wavelength`,
  20687.5 AS `proposed_max_wavelength`,
  ps.`zeropoint_jansky` AS `current_zeropoint_jansky`
FROM `moca_photometry_systems` ps
WHERE ps.`moca_psid` = 'cpapir_heimag';

UPDATE `moca_photometry_systems`
SET
  `average_wavelength` = COALESCE(`average_wavelength`, 20620),
  `min_wavelength` = COALESCE(`min_wavelength`, 20552.5),
  `max_wavelength` = COALESCE(`max_wavelength`, 20687.5),
  `bandpass_file` = COALESCE(`bandpass_file`, 'OMM CPAPIR rectangular approximation HeI; https://www.omm-astro.ca/en/for-observers/instruments-guide/')
WHERE `moca_psid` = 'cpapir_heimag';

CREATE TEMPORARY TABLE IF NOT EXISTS `_mocaviz_cpapir_bandpass_stage` (
  `moca_psid` varchar(128) NOT NULL,
  `wavelength_angstrom` double NOT NULL,
  `relative_spectral_response` double NOT NULL
) ENGINE=Memory;
DELETE FROM `_mocaviz_cpapir_bandpass_stage`;
INSERT INTO `_mocaviz_cpapir_bandpass_stage`
  (`moca_psid`, `wavelength_angstrom`, `relative_spectral_response`)
VALUES
  ('cpapir_heimag', 20545, 1),
  ('cpapir_heimag', 20546.5, 1),
  ('cpapir_heimag', 20548, 1),
  ('cpapir_heimag', 20549.5, 1),
  ('cpapir_heimag', 20551, 1),
  ('cpapir_heimag', 20552.5, 1),
  ('cpapir_heimag', 20554, 1),
  ('cpapir_heimag', 20555.5, 1),
  ('cpapir_heimag', 20557, 1),
  ('cpapir_heimag', 20558.5, 1),
  ('cpapir_heimag', 20560, 1),
  ('cpapir_heimag', 20561.5, 1),
  ('cpapir_heimag', 20563, 1),
  ('cpapir_heimag', 20564.5, 1),
  ('cpapir_heimag', 20566, 1),
  ('cpapir_heimag', 20567.5, 1),
  ('cpapir_heimag', 20569, 1),
  ('cpapir_heimag', 20570.5, 1),
  ('cpapir_heimag', 20572, 1),
  ('cpapir_heimag', 20573.5, 1),
  ('cpapir_heimag', 20575, 1),
  ('cpapir_heimag', 20576.5, 1),
  ('cpapir_heimag', 20578, 1),
  ('cpapir_heimag', 20579.5, 1),
  ('cpapir_heimag', 20581, 1),
  ('cpapir_heimag', 20582.5, 1),
  ('cpapir_heimag', 20584, 1),
  ('cpapir_heimag', 20585.5, 1),
  ('cpapir_heimag', 20587, 1),
  ('cpapir_heimag', 20588.5, 1),
  ('cpapir_heimag', 20590, 1),
  ('cpapir_heimag', 20591.5, 1),
  ('cpapir_heimag', 20593, 1),
  ('cpapir_heimag', 20594.5, 1),
  ('cpapir_heimag', 20596, 1),
  ('cpapir_heimag', 20597.5, 1),
  ('cpapir_heimag', 20599, 1),
  ('cpapir_heimag', 20600.5, 1),
  ('cpapir_heimag', 20602, 1),
  ('cpapir_heimag', 20603.5, 1),
  ('cpapir_heimag', 20605, 1),
  ('cpapir_heimag', 20606.5, 1),
  ('cpapir_heimag', 20608, 1),
  ('cpapir_heimag', 20609.5, 1),
  ('cpapir_heimag', 20611, 1),
  ('cpapir_heimag', 20612.5, 1),
  ('cpapir_heimag', 20614, 1),
  ('cpapir_heimag', 20615.5, 1),
  ('cpapir_heimag', 20617, 1),
  ('cpapir_heimag', 20618.5, 1),
  ('cpapir_heimag', 20620, 1),
  ('cpapir_heimag', 20621.5, 1),
  ('cpapir_heimag', 20623, 1),
  ('cpapir_heimag', 20624.5, 1),
  ('cpapir_heimag', 20626, 1),
  ('cpapir_heimag', 20627.5, 1),
  ('cpapir_heimag', 20629, 1),
  ('cpapir_heimag', 20630.5, 1),
  ('cpapir_heimag', 20632, 1),
  ('cpapir_heimag', 20633.5, 1),
  ('cpapir_heimag', 20635, 1),
  ('cpapir_heimag', 20636.5, 1),
  ('cpapir_heimag', 20638, 1),
  ('cpapir_heimag', 20639.5, 1),
  ('cpapir_heimag', 20641, 1),
  ('cpapir_heimag', 20642.5, 1),
  ('cpapir_heimag', 20644, 1),
  ('cpapir_heimag', 20645.5, 1),
  ('cpapir_heimag', 20647, 1),
  ('cpapir_heimag', 20648.5, 1),
  ('cpapir_heimag', 20650, 1),
  ('cpapir_heimag', 20651.5, 1),
  ('cpapir_heimag', 20653, 1),
  ('cpapir_heimag', 20654.5, 1),
  ('cpapir_heimag', 20656, 1),
  ('cpapir_heimag', 20657.5, 1),
  ('cpapir_heimag', 20659, 1),
  ('cpapir_heimag', 20660.5, 1),
  ('cpapir_heimag', 20662, 1),
  ('cpapir_heimag', 20663.5, 1),
  ('cpapir_heimag', 20665, 1),
  ('cpapir_heimag', 20666.5, 1),
  ('cpapir_heimag', 20668, 1),
  ('cpapir_heimag', 20669.5, 1),
  ('cpapir_heimag', 20671, 1),
  ('cpapir_heimag', 20672.5, 1),
  ('cpapir_heimag', 20674, 1),
  ('cpapir_heimag', 20675.5, 1),
  ('cpapir_heimag', 20677, 1),
  ('cpapir_heimag', 20678.5, 1),
  ('cpapir_heimag', 20680, 1),
  ('cpapir_heimag', 20681.5, 1),
  ('cpapir_heimag', 20683, 1),
  ('cpapir_heimag', 20684.5, 1),
  ('cpapir_heimag', 20686, 1),
  ('cpapir_heimag', 20687.5, 1),
  ('cpapir_heimag', 20689, 1),
  ('cpapir_heimag', 20690.5, 1),
  ('cpapir_heimag', 20692, 1),
  ('cpapir_heimag', 20693.5, 1),
  ('cpapir_heimag', 20695, 1);
INSERT INTO `data_photometric_bandpasses`
  (`moca_psid`, `wavelength_angstrom`, `relative_spectral_response`)
SELECT
  stage.`moca_psid`,
  stage.`wavelength_angstrom`,
  stage.`relative_spectral_response`
FROM `_mocaviz_cpapir_bandpass_stage` stage
WHERE NOT EXISTS (
  SELECT 1
  FROM `data_photometric_bandpasses` existing
  WHERE existing.`moca_psid` = 'cpapir_heimag'
  LIMIT 1
)
ORDER BY stage.`wavelength_angstrom`;
DELETE FROM `_mocaviz_cpapir_bandpass_stage`;

-- cpapir_civmag: CIV, lambda=2.081 um, Delta_lambda=0.02 um
SELECT
  'cpapir_civmag' AS `moca_psid`,
  ps.`average_wavelength` AS `current_average_wavelength`,
  20810 AS `proposed_average_wavelength`,
  ps.`min_wavelength` AS `current_min_wavelength`,
  20720 AS `proposed_min_wavelength`,
  ps.`max_wavelength` AS `current_max_wavelength`,
  20900 AS `proposed_max_wavelength`,
  ps.`zeropoint_jansky` AS `current_zeropoint_jansky`
FROM `moca_photometry_systems` ps
WHERE ps.`moca_psid` = 'cpapir_civmag';

UPDATE `moca_photometry_systems`
SET
  `average_wavelength` = COALESCE(`average_wavelength`, 20810),
  `min_wavelength` = COALESCE(`min_wavelength`, 20720),
  `max_wavelength` = COALESCE(`max_wavelength`, 20900),
  `bandpass_file` = COALESCE(`bandpass_file`, 'OMM CPAPIR rectangular approximation CIV; https://www.omm-astro.ca/en/for-observers/instruments-guide/')
WHERE `moca_psid` = 'cpapir_civmag';

CREATE TEMPORARY TABLE IF NOT EXISTS `_mocaviz_cpapir_bandpass_stage` (
  `moca_psid` varchar(128) NOT NULL,
  `wavelength_angstrom` double NOT NULL,
  `relative_spectral_response` double NOT NULL
) ENGINE=Memory;
DELETE FROM `_mocaviz_cpapir_bandpass_stage`;
INSERT INTO `_mocaviz_cpapir_bandpass_stage`
  (`moca_psid`, `wavelength_angstrom`, `relative_spectral_response`)
VALUES
  ('cpapir_civmag', 20710, 1),
  ('cpapir_civmag', 20712, 1),
  ('cpapir_civmag', 20714, 1),
  ('cpapir_civmag', 20716, 1),
  ('cpapir_civmag', 20718, 1),
  ('cpapir_civmag', 20720, 1),
  ('cpapir_civmag', 20722, 1),
  ('cpapir_civmag', 20724, 1),
  ('cpapir_civmag', 20726, 1),
  ('cpapir_civmag', 20728, 1),
  ('cpapir_civmag', 20730, 1),
  ('cpapir_civmag', 20732, 1),
  ('cpapir_civmag', 20734, 1),
  ('cpapir_civmag', 20736, 1),
  ('cpapir_civmag', 20738, 1),
  ('cpapir_civmag', 20740, 1),
  ('cpapir_civmag', 20742, 1),
  ('cpapir_civmag', 20744, 1),
  ('cpapir_civmag', 20746, 1),
  ('cpapir_civmag', 20748, 1),
  ('cpapir_civmag', 20750, 1),
  ('cpapir_civmag', 20752, 1),
  ('cpapir_civmag', 20754, 1),
  ('cpapir_civmag', 20756, 1),
  ('cpapir_civmag', 20758, 1),
  ('cpapir_civmag', 20760, 1),
  ('cpapir_civmag', 20762, 1),
  ('cpapir_civmag', 20764, 1),
  ('cpapir_civmag', 20766, 1),
  ('cpapir_civmag', 20768, 1),
  ('cpapir_civmag', 20770, 1),
  ('cpapir_civmag', 20772, 1),
  ('cpapir_civmag', 20774, 1),
  ('cpapir_civmag', 20776, 1),
  ('cpapir_civmag', 20778, 1),
  ('cpapir_civmag', 20780, 1),
  ('cpapir_civmag', 20782, 1),
  ('cpapir_civmag', 20784, 1),
  ('cpapir_civmag', 20786, 1),
  ('cpapir_civmag', 20788, 1),
  ('cpapir_civmag', 20790, 1),
  ('cpapir_civmag', 20792, 1),
  ('cpapir_civmag', 20794, 1),
  ('cpapir_civmag', 20796, 1),
  ('cpapir_civmag', 20798, 1),
  ('cpapir_civmag', 20800, 1),
  ('cpapir_civmag', 20802, 1),
  ('cpapir_civmag', 20804, 1),
  ('cpapir_civmag', 20806, 1),
  ('cpapir_civmag', 20808, 1),
  ('cpapir_civmag', 20810, 1),
  ('cpapir_civmag', 20812, 1),
  ('cpapir_civmag', 20814, 1),
  ('cpapir_civmag', 20816, 1),
  ('cpapir_civmag', 20818, 1),
  ('cpapir_civmag', 20820, 1),
  ('cpapir_civmag', 20822, 1),
  ('cpapir_civmag', 20824, 1),
  ('cpapir_civmag', 20826, 1),
  ('cpapir_civmag', 20828, 1),
  ('cpapir_civmag', 20830, 1),
  ('cpapir_civmag', 20832, 1),
  ('cpapir_civmag', 20834, 1),
  ('cpapir_civmag', 20836, 1),
  ('cpapir_civmag', 20838, 1),
  ('cpapir_civmag', 20840, 1),
  ('cpapir_civmag', 20842, 1),
  ('cpapir_civmag', 20844, 1),
  ('cpapir_civmag', 20846, 1),
  ('cpapir_civmag', 20848, 1),
  ('cpapir_civmag', 20850, 1),
  ('cpapir_civmag', 20852, 1),
  ('cpapir_civmag', 20854, 1),
  ('cpapir_civmag', 20856, 1),
  ('cpapir_civmag', 20858, 1),
  ('cpapir_civmag', 20860, 1),
  ('cpapir_civmag', 20862, 1),
  ('cpapir_civmag', 20864, 1),
  ('cpapir_civmag', 20866, 1),
  ('cpapir_civmag', 20868, 1),
  ('cpapir_civmag', 20870, 1),
  ('cpapir_civmag', 20872, 1),
  ('cpapir_civmag', 20874, 1),
  ('cpapir_civmag', 20876, 1),
  ('cpapir_civmag', 20878, 1),
  ('cpapir_civmag', 20880, 1),
  ('cpapir_civmag', 20882, 1),
  ('cpapir_civmag', 20884, 1),
  ('cpapir_civmag', 20886, 1),
  ('cpapir_civmag', 20888, 1),
  ('cpapir_civmag', 20890, 1),
  ('cpapir_civmag', 20892, 1),
  ('cpapir_civmag', 20894, 1),
  ('cpapir_civmag', 20896, 1),
  ('cpapir_civmag', 20898, 1),
  ('cpapir_civmag', 20900, 1),
  ('cpapir_civmag', 20902, 1),
  ('cpapir_civmag', 20904, 1),
  ('cpapir_civmag', 20906, 1),
  ('cpapir_civmag', 20908, 1),
  ('cpapir_civmag', 20910, 1);
INSERT INTO `data_photometric_bandpasses`
  (`moca_psid`, `wavelength_angstrom`, `relative_spectral_response`)
SELECT
  stage.`moca_psid`,
  stage.`wavelength_angstrom`,
  stage.`relative_spectral_response`
FROM `_mocaviz_cpapir_bandpass_stage` stage
WHERE NOT EXISTS (
  SELECT 1
  FROM `data_photometric_bandpasses` existing
  WHERE existing.`moca_psid` = 'cpapir_civmag'
  LIMIT 1
)
ORDER BY stage.`wavelength_angstrom`;
DELETE FROM `_mocaviz_cpapir_bandpass_stage`;

-- cpapir_kmag: Ks, lambda=2.15 um, Delta_lambda=0.3 um
SELECT
  'cpapir_kmag' AS `moca_psid`,
  ps.`average_wavelength` AS `current_average_wavelength`,
  21500 AS `proposed_average_wavelength`,
  ps.`min_wavelength` AS `current_min_wavelength`,
  20150 AS `proposed_min_wavelength`,
  ps.`max_wavelength` AS `current_max_wavelength`,
  22850 AS `proposed_max_wavelength`,
  ps.`zeropoint_jansky` AS `current_zeropoint_jansky`
FROM `moca_photometry_systems` ps
WHERE ps.`moca_psid` = 'cpapir_kmag';

UPDATE `moca_photometry_systems`
SET
  `average_wavelength` = COALESCE(`average_wavelength`, 21500),
  `min_wavelength` = COALESCE(`min_wavelength`, 20150),
  `max_wavelength` = COALESCE(`max_wavelength`, 22850),
  `bandpass_file` = COALESCE(`bandpass_file`, 'OMM CPAPIR rectangular approximation Ks; https://www.omm-astro.ca/en/for-observers/instruments-guide/')
WHERE `moca_psid` = 'cpapir_kmag';

CREATE TEMPORARY TABLE IF NOT EXISTS `_mocaviz_cpapir_bandpass_stage` (
  `moca_psid` varchar(128) NOT NULL,
  `wavelength_angstrom` double NOT NULL,
  `relative_spectral_response` double NOT NULL
) ENGINE=Memory;
DELETE FROM `_mocaviz_cpapir_bandpass_stage`;
INSERT INTO `_mocaviz_cpapir_bandpass_stage`
  (`moca_psid`, `wavelength_angstrom`, `relative_spectral_response`)
VALUES
  ('cpapir_kmag', 20000, 1),
  ('cpapir_kmag', 20030, 1),
  ('cpapir_kmag', 20060, 1),
  ('cpapir_kmag', 20090, 1),
  ('cpapir_kmag', 20120, 1),
  ('cpapir_kmag', 20150, 1),
  ('cpapir_kmag', 20180, 1),
  ('cpapir_kmag', 20210, 1),
  ('cpapir_kmag', 20240, 1),
  ('cpapir_kmag', 20270, 1),
  ('cpapir_kmag', 20300, 1),
  ('cpapir_kmag', 20330, 1),
  ('cpapir_kmag', 20360, 1),
  ('cpapir_kmag', 20390, 1),
  ('cpapir_kmag', 20420, 1),
  ('cpapir_kmag', 20450, 1),
  ('cpapir_kmag', 20480, 1),
  ('cpapir_kmag', 20510, 1),
  ('cpapir_kmag', 20540, 1),
  ('cpapir_kmag', 20570, 1),
  ('cpapir_kmag', 20600, 1),
  ('cpapir_kmag', 20630, 1),
  ('cpapir_kmag', 20660, 1),
  ('cpapir_kmag', 20690, 1),
  ('cpapir_kmag', 20720, 1),
  ('cpapir_kmag', 20750, 1),
  ('cpapir_kmag', 20780, 1),
  ('cpapir_kmag', 20810, 1),
  ('cpapir_kmag', 20840, 1),
  ('cpapir_kmag', 20870, 1),
  ('cpapir_kmag', 20900, 1),
  ('cpapir_kmag', 20930, 1),
  ('cpapir_kmag', 20960, 1),
  ('cpapir_kmag', 20990, 1),
  ('cpapir_kmag', 21020, 1),
  ('cpapir_kmag', 21050, 1),
  ('cpapir_kmag', 21080, 1),
  ('cpapir_kmag', 21110, 1),
  ('cpapir_kmag', 21140, 1),
  ('cpapir_kmag', 21170, 1),
  ('cpapir_kmag', 21200, 1),
  ('cpapir_kmag', 21230, 1),
  ('cpapir_kmag', 21260, 1),
  ('cpapir_kmag', 21290, 1),
  ('cpapir_kmag', 21320, 1),
  ('cpapir_kmag', 21350, 1),
  ('cpapir_kmag', 21380, 1),
  ('cpapir_kmag', 21410, 1),
  ('cpapir_kmag', 21440, 1),
  ('cpapir_kmag', 21470, 1),
  ('cpapir_kmag', 21500, 1),
  ('cpapir_kmag', 21530, 1),
  ('cpapir_kmag', 21560, 1),
  ('cpapir_kmag', 21590, 1),
  ('cpapir_kmag', 21620, 1),
  ('cpapir_kmag', 21650, 1),
  ('cpapir_kmag', 21680, 1),
  ('cpapir_kmag', 21710, 1),
  ('cpapir_kmag', 21740, 1),
  ('cpapir_kmag', 21770, 1),
  ('cpapir_kmag', 21800, 1),
  ('cpapir_kmag', 21830, 1),
  ('cpapir_kmag', 21860, 1),
  ('cpapir_kmag', 21890, 1),
  ('cpapir_kmag', 21920, 1),
  ('cpapir_kmag', 21950, 1),
  ('cpapir_kmag', 21980, 1),
  ('cpapir_kmag', 22010, 1),
  ('cpapir_kmag', 22040, 1),
  ('cpapir_kmag', 22070, 1),
  ('cpapir_kmag', 22100, 1),
  ('cpapir_kmag', 22130, 1),
  ('cpapir_kmag', 22160, 1),
  ('cpapir_kmag', 22190, 1),
  ('cpapir_kmag', 22220, 1),
  ('cpapir_kmag', 22250, 1),
  ('cpapir_kmag', 22280, 1),
  ('cpapir_kmag', 22310, 1),
  ('cpapir_kmag', 22340, 1),
  ('cpapir_kmag', 22370, 1),
  ('cpapir_kmag', 22400, 1),
  ('cpapir_kmag', 22430, 1),
  ('cpapir_kmag', 22460, 1),
  ('cpapir_kmag', 22490, 1),
  ('cpapir_kmag', 22520, 1),
  ('cpapir_kmag', 22550, 1),
  ('cpapir_kmag', 22580, 1),
  ('cpapir_kmag', 22610, 1),
  ('cpapir_kmag', 22640, 1),
  ('cpapir_kmag', 22670, 1),
  ('cpapir_kmag', 22700, 1),
  ('cpapir_kmag', 22730, 1),
  ('cpapir_kmag', 22760, 1),
  ('cpapir_kmag', 22790, 1),
  ('cpapir_kmag', 22820, 1),
  ('cpapir_kmag', 22850, 1),
  ('cpapir_kmag', 22880, 1),
  ('cpapir_kmag', 22910, 1),
  ('cpapir_kmag', 22940, 1),
  ('cpapir_kmag', 22970, 1),
  ('cpapir_kmag', 23000, 1);
INSERT INTO `data_photometric_bandpasses`
  (`moca_psid`, `wavelength_angstrom`, `relative_spectral_response`)
SELECT
  stage.`moca_psid`,
  stage.`wavelength_angstrom`,
  stage.`relative_spectral_response`
FROM `_mocaviz_cpapir_bandpass_stage` stage
WHERE NOT EXISTS (
  SELECT 1
  FROM `data_photometric_bandpasses` existing
  WHERE existing.`moca_psid` = 'cpapir_kmag'
  LIMIT 1
)
ORDER BY stage.`wavelength_angstrom`;
DELETE FROM `_mocaviz_cpapir_bandpass_stage`;

-- cpapir_brgammamag: Brackett gamma, lambda=2.165 um, Delta_lambda=0.02 um
SELECT
  'cpapir_brgammamag' AS `moca_psid`,
  ps.`average_wavelength` AS `current_average_wavelength`,
  21650 AS `proposed_average_wavelength`,
  ps.`min_wavelength` AS `current_min_wavelength`,
  21560 AS `proposed_min_wavelength`,
  ps.`max_wavelength` AS `current_max_wavelength`,
  21740 AS `proposed_max_wavelength`,
  ps.`zeropoint_jansky` AS `current_zeropoint_jansky`
FROM `moca_photometry_systems` ps
WHERE ps.`moca_psid` = 'cpapir_brgammamag';

UPDATE `moca_photometry_systems`
SET
  `average_wavelength` = COALESCE(`average_wavelength`, 21650),
  `min_wavelength` = COALESCE(`min_wavelength`, 21560),
  `max_wavelength` = COALESCE(`max_wavelength`, 21740),
  `bandpass_file` = COALESCE(`bandpass_file`, 'OMM CPAPIR rectangular approximation Brackett gamma; https://www.omm-astro.ca/en/for-observers/instruments-guide/')
WHERE `moca_psid` = 'cpapir_brgammamag';

CREATE TEMPORARY TABLE IF NOT EXISTS `_mocaviz_cpapir_bandpass_stage` (
  `moca_psid` varchar(128) NOT NULL,
  `wavelength_angstrom` double NOT NULL,
  `relative_spectral_response` double NOT NULL
) ENGINE=Memory;
DELETE FROM `_mocaviz_cpapir_bandpass_stage`;
INSERT INTO `_mocaviz_cpapir_bandpass_stage`
  (`moca_psid`, `wavelength_angstrom`, `relative_spectral_response`)
VALUES
  ('cpapir_brgammamag', 21550, 1),
  ('cpapir_brgammamag', 21552, 1),
  ('cpapir_brgammamag', 21554, 1),
  ('cpapir_brgammamag', 21556, 1),
  ('cpapir_brgammamag', 21558, 1),
  ('cpapir_brgammamag', 21560, 1),
  ('cpapir_brgammamag', 21562, 1),
  ('cpapir_brgammamag', 21564, 1),
  ('cpapir_brgammamag', 21566, 1),
  ('cpapir_brgammamag', 21568, 1),
  ('cpapir_brgammamag', 21570, 1),
  ('cpapir_brgammamag', 21572, 1),
  ('cpapir_brgammamag', 21574, 1),
  ('cpapir_brgammamag', 21576, 1),
  ('cpapir_brgammamag', 21578, 1),
  ('cpapir_brgammamag', 21580, 1),
  ('cpapir_brgammamag', 21582, 1),
  ('cpapir_brgammamag', 21584, 1),
  ('cpapir_brgammamag', 21586, 1),
  ('cpapir_brgammamag', 21588, 1),
  ('cpapir_brgammamag', 21590, 1),
  ('cpapir_brgammamag', 21592, 1),
  ('cpapir_brgammamag', 21594, 1),
  ('cpapir_brgammamag', 21596, 1),
  ('cpapir_brgammamag', 21598, 1),
  ('cpapir_brgammamag', 21600, 1),
  ('cpapir_brgammamag', 21602, 1),
  ('cpapir_brgammamag', 21604, 1),
  ('cpapir_brgammamag', 21606, 1),
  ('cpapir_brgammamag', 21608, 1),
  ('cpapir_brgammamag', 21610, 1),
  ('cpapir_brgammamag', 21612, 1),
  ('cpapir_brgammamag', 21614, 1),
  ('cpapir_brgammamag', 21616, 1),
  ('cpapir_brgammamag', 21618, 1),
  ('cpapir_brgammamag', 21620, 1),
  ('cpapir_brgammamag', 21622, 1),
  ('cpapir_brgammamag', 21624, 1),
  ('cpapir_brgammamag', 21626, 1),
  ('cpapir_brgammamag', 21628, 1),
  ('cpapir_brgammamag', 21630, 1),
  ('cpapir_brgammamag', 21632, 1),
  ('cpapir_brgammamag', 21634, 1),
  ('cpapir_brgammamag', 21636, 1),
  ('cpapir_brgammamag', 21638, 1),
  ('cpapir_brgammamag', 21640, 1),
  ('cpapir_brgammamag', 21642, 1),
  ('cpapir_brgammamag', 21644, 1),
  ('cpapir_brgammamag', 21646, 1),
  ('cpapir_brgammamag', 21648, 1),
  ('cpapir_brgammamag', 21650, 1),
  ('cpapir_brgammamag', 21652, 1),
  ('cpapir_brgammamag', 21654, 1),
  ('cpapir_brgammamag', 21656, 1),
  ('cpapir_brgammamag', 21658, 1),
  ('cpapir_brgammamag', 21660, 1),
  ('cpapir_brgammamag', 21662, 1),
  ('cpapir_brgammamag', 21664, 1),
  ('cpapir_brgammamag', 21666, 1),
  ('cpapir_brgammamag', 21668, 1),
  ('cpapir_brgammamag', 21670, 1),
  ('cpapir_brgammamag', 21672, 1),
  ('cpapir_brgammamag', 21674, 1),
  ('cpapir_brgammamag', 21676, 1),
  ('cpapir_brgammamag', 21678, 1),
  ('cpapir_brgammamag', 21680, 1),
  ('cpapir_brgammamag', 21682, 1),
  ('cpapir_brgammamag', 21684, 1),
  ('cpapir_brgammamag', 21686, 1),
  ('cpapir_brgammamag', 21688, 1),
  ('cpapir_brgammamag', 21690, 1),
  ('cpapir_brgammamag', 21692, 1),
  ('cpapir_brgammamag', 21694, 1),
  ('cpapir_brgammamag', 21696, 1),
  ('cpapir_brgammamag', 21698, 1),
  ('cpapir_brgammamag', 21700, 1),
  ('cpapir_brgammamag', 21702, 1),
  ('cpapir_brgammamag', 21704, 1),
  ('cpapir_brgammamag', 21706, 1),
  ('cpapir_brgammamag', 21708, 1),
  ('cpapir_brgammamag', 21710, 1),
  ('cpapir_brgammamag', 21712, 1),
  ('cpapir_brgammamag', 21714, 1),
  ('cpapir_brgammamag', 21716, 1),
  ('cpapir_brgammamag', 21718, 1),
  ('cpapir_brgammamag', 21720, 1),
  ('cpapir_brgammamag', 21722, 1),
  ('cpapir_brgammamag', 21724, 1),
  ('cpapir_brgammamag', 21726, 1),
  ('cpapir_brgammamag', 21728, 1),
  ('cpapir_brgammamag', 21730, 1),
  ('cpapir_brgammamag', 21732, 1),
  ('cpapir_brgammamag', 21734, 1),
  ('cpapir_brgammamag', 21736, 1),
  ('cpapir_brgammamag', 21738, 1),
  ('cpapir_brgammamag', 21740, 1),
  ('cpapir_brgammamag', 21742, 1),
  ('cpapir_brgammamag', 21744, 1),
  ('cpapir_brgammamag', 21746, 1),
  ('cpapir_brgammamag', 21748, 1),
  ('cpapir_brgammamag', 21750, 1);
INSERT INTO `data_photometric_bandpasses`
  (`moca_psid`, `wavelength_angstrom`, `relative_spectral_response`)
SELECT
  stage.`moca_psid`,
  stage.`wavelength_angstrom`,
  stage.`relative_spectral_response`
FROM `_mocaviz_cpapir_bandpass_stage` stage
WHERE NOT EXISTS (
  SELECT 1
  FROM `data_photometric_bandpasses` existing
  WHERE existing.`moca_psid` = 'cpapir_brgammamag'
  LIMIT 1
)
ORDER BY stage.`wavelength_angstrom`;
DELETE FROM `_mocaviz_cpapir_bandpass_stage`;

-- cpapir_heiimag: HeII, lambda=2.192 um, Delta_lambda=0.04 um
SELECT
  'cpapir_heiimag' AS `moca_psid`,
  ps.`average_wavelength` AS `current_average_wavelength`,
  21920 AS `proposed_average_wavelength`,
  ps.`min_wavelength` AS `current_min_wavelength`,
  21740 AS `proposed_min_wavelength`,
  ps.`max_wavelength` AS `current_max_wavelength`,
  22100 AS `proposed_max_wavelength`,
  ps.`zeropoint_jansky` AS `current_zeropoint_jansky`
FROM `moca_photometry_systems` ps
WHERE ps.`moca_psid` = 'cpapir_heiimag';

UPDATE `moca_photometry_systems`
SET
  `average_wavelength` = COALESCE(`average_wavelength`, 21920),
  `min_wavelength` = COALESCE(`min_wavelength`, 21740),
  `max_wavelength` = COALESCE(`max_wavelength`, 22100),
  `bandpass_file` = COALESCE(`bandpass_file`, 'OMM CPAPIR rectangular approximation HeII; https://www.omm-astro.ca/en/for-observers/instruments-guide/')
WHERE `moca_psid` = 'cpapir_heiimag';

CREATE TEMPORARY TABLE IF NOT EXISTS `_mocaviz_cpapir_bandpass_stage` (
  `moca_psid` varchar(128) NOT NULL,
  `wavelength_angstrom` double NOT NULL,
  `relative_spectral_response` double NOT NULL
) ENGINE=Memory;
DELETE FROM `_mocaviz_cpapir_bandpass_stage`;
INSERT INTO `_mocaviz_cpapir_bandpass_stage`
  (`moca_psid`, `wavelength_angstrom`, `relative_spectral_response`)
VALUES
  ('cpapir_heiimag', 21720, 1),
  ('cpapir_heiimag', 21724, 1),
  ('cpapir_heiimag', 21728, 1),
  ('cpapir_heiimag', 21732, 1),
  ('cpapir_heiimag', 21736, 1),
  ('cpapir_heiimag', 21740, 1),
  ('cpapir_heiimag', 21744, 1),
  ('cpapir_heiimag', 21748, 1),
  ('cpapir_heiimag', 21752, 1),
  ('cpapir_heiimag', 21756, 1),
  ('cpapir_heiimag', 21760, 1),
  ('cpapir_heiimag', 21764, 1),
  ('cpapir_heiimag', 21768, 1),
  ('cpapir_heiimag', 21772, 1),
  ('cpapir_heiimag', 21776, 1),
  ('cpapir_heiimag', 21780, 1),
  ('cpapir_heiimag', 21784, 1),
  ('cpapir_heiimag', 21788, 1),
  ('cpapir_heiimag', 21792, 1),
  ('cpapir_heiimag', 21796, 1),
  ('cpapir_heiimag', 21800, 1),
  ('cpapir_heiimag', 21804, 1),
  ('cpapir_heiimag', 21808, 1),
  ('cpapir_heiimag', 21812, 1),
  ('cpapir_heiimag', 21816, 1),
  ('cpapir_heiimag', 21820, 1),
  ('cpapir_heiimag', 21824, 1),
  ('cpapir_heiimag', 21828, 1),
  ('cpapir_heiimag', 21832, 1),
  ('cpapir_heiimag', 21836, 1),
  ('cpapir_heiimag', 21840, 1),
  ('cpapir_heiimag', 21844, 1),
  ('cpapir_heiimag', 21848, 1),
  ('cpapir_heiimag', 21852, 1),
  ('cpapir_heiimag', 21856, 1),
  ('cpapir_heiimag', 21860, 1),
  ('cpapir_heiimag', 21864, 1),
  ('cpapir_heiimag', 21868, 1),
  ('cpapir_heiimag', 21872, 1),
  ('cpapir_heiimag', 21876, 1),
  ('cpapir_heiimag', 21880, 1),
  ('cpapir_heiimag', 21884, 1),
  ('cpapir_heiimag', 21888, 1),
  ('cpapir_heiimag', 21892, 1),
  ('cpapir_heiimag', 21896, 1),
  ('cpapir_heiimag', 21900, 1),
  ('cpapir_heiimag', 21904, 1),
  ('cpapir_heiimag', 21908, 1),
  ('cpapir_heiimag', 21912, 1),
  ('cpapir_heiimag', 21916, 1),
  ('cpapir_heiimag', 21920, 1),
  ('cpapir_heiimag', 21924, 1),
  ('cpapir_heiimag', 21928, 1),
  ('cpapir_heiimag', 21932, 1),
  ('cpapir_heiimag', 21936, 1),
  ('cpapir_heiimag', 21940, 1),
  ('cpapir_heiimag', 21944, 1),
  ('cpapir_heiimag', 21948, 1),
  ('cpapir_heiimag', 21952, 1),
  ('cpapir_heiimag', 21956, 1),
  ('cpapir_heiimag', 21960, 1),
  ('cpapir_heiimag', 21964, 1),
  ('cpapir_heiimag', 21968, 1),
  ('cpapir_heiimag', 21972, 1),
  ('cpapir_heiimag', 21976, 1),
  ('cpapir_heiimag', 21980, 1),
  ('cpapir_heiimag', 21984, 1),
  ('cpapir_heiimag', 21988, 1),
  ('cpapir_heiimag', 21992, 1),
  ('cpapir_heiimag', 21996, 1),
  ('cpapir_heiimag', 22000, 1),
  ('cpapir_heiimag', 22004, 1),
  ('cpapir_heiimag', 22008, 1),
  ('cpapir_heiimag', 22012, 1),
  ('cpapir_heiimag', 22016, 1),
  ('cpapir_heiimag', 22020, 1),
  ('cpapir_heiimag', 22024, 1),
  ('cpapir_heiimag', 22028, 1),
  ('cpapir_heiimag', 22032, 1),
  ('cpapir_heiimag', 22036, 1),
  ('cpapir_heiimag', 22040, 1),
  ('cpapir_heiimag', 22044, 1),
  ('cpapir_heiimag', 22048, 1),
  ('cpapir_heiimag', 22052, 1),
  ('cpapir_heiimag', 22056, 1),
  ('cpapir_heiimag', 22060, 1),
  ('cpapir_heiimag', 22064, 1),
  ('cpapir_heiimag', 22068, 1),
  ('cpapir_heiimag', 22072, 1),
  ('cpapir_heiimag', 22076, 1),
  ('cpapir_heiimag', 22080, 1),
  ('cpapir_heiimag', 22084, 1),
  ('cpapir_heiimag', 22088, 1),
  ('cpapir_heiimag', 22092, 1),
  ('cpapir_heiimag', 22096, 1),
  ('cpapir_heiimag', 22100, 1),
  ('cpapir_heiimag', 22104, 1),
  ('cpapir_heiimag', 22108, 1),
  ('cpapir_heiimag', 22112, 1),
  ('cpapir_heiimag', 22116, 1),
  ('cpapir_heiimag', 22120, 1);
INSERT INTO `data_photometric_bandpasses`
  (`moca_psid`, `wavelength_angstrom`, `relative_spectral_response`)
SELECT
  stage.`moca_psid`,
  stage.`wavelength_angstrom`,
  stage.`relative_spectral_response`
FROM `_mocaviz_cpapir_bandpass_stage` stage
WHERE NOT EXISTS (
  SELECT 1
  FROM `data_photometric_bandpasses` existing
  WHERE existing.`moca_psid` = 'cpapir_heiimag'
  LIMIT 1
)
ORDER BY stage.`wavelength_angstrom`;
DELETE FROM `_mocaviz_cpapir_bandpass_stage`;

-- cpapir_cont1mag: CONT1, lambda=2.255 um, Delta_lambda=0.1 um
SELECT
  'cpapir_cont1mag' AS `moca_psid`,
  ps.`average_wavelength` AS `current_average_wavelength`,
  22550 AS `proposed_average_wavelength`,
  ps.`min_wavelength` AS `current_min_wavelength`,
  22100 AS `proposed_min_wavelength`,
  ps.`max_wavelength` AS `current_max_wavelength`,
  23000 AS `proposed_max_wavelength`,
  ps.`zeropoint_jansky` AS `current_zeropoint_jansky`
FROM `moca_photometry_systems` ps
WHERE ps.`moca_psid` = 'cpapir_cont1mag';

UPDATE `moca_photometry_systems`
SET
  `average_wavelength` = COALESCE(`average_wavelength`, 22550),
  `min_wavelength` = COALESCE(`min_wavelength`, 22100),
  `max_wavelength` = COALESCE(`max_wavelength`, 23000),
  `bandpass_file` = COALESCE(`bandpass_file`, 'OMM CPAPIR rectangular approximation CONT1; https://www.omm-astro.ca/en/for-observers/instruments-guide/')
WHERE `moca_psid` = 'cpapir_cont1mag';

CREATE TEMPORARY TABLE IF NOT EXISTS `_mocaviz_cpapir_bandpass_stage` (
  `moca_psid` varchar(128) NOT NULL,
  `wavelength_angstrom` double NOT NULL,
  `relative_spectral_response` double NOT NULL
) ENGINE=Memory;
DELETE FROM `_mocaviz_cpapir_bandpass_stage`;
INSERT INTO `_mocaviz_cpapir_bandpass_stage`
  (`moca_psid`, `wavelength_angstrom`, `relative_spectral_response`)
VALUES
  ('cpapir_cont1mag', 22050, 1),
  ('cpapir_cont1mag', 22060, 1),
  ('cpapir_cont1mag', 22070, 1),
  ('cpapir_cont1mag', 22080, 1),
  ('cpapir_cont1mag', 22090, 1),
  ('cpapir_cont1mag', 22100, 1),
  ('cpapir_cont1mag', 22110, 1),
  ('cpapir_cont1mag', 22120, 1),
  ('cpapir_cont1mag', 22130, 1),
  ('cpapir_cont1mag', 22140, 1),
  ('cpapir_cont1mag', 22150, 1),
  ('cpapir_cont1mag', 22160, 1),
  ('cpapir_cont1mag', 22170, 1),
  ('cpapir_cont1mag', 22180, 1),
  ('cpapir_cont1mag', 22190, 1),
  ('cpapir_cont1mag', 22200, 1),
  ('cpapir_cont1mag', 22210, 1),
  ('cpapir_cont1mag', 22220, 1),
  ('cpapir_cont1mag', 22230, 1),
  ('cpapir_cont1mag', 22240, 1),
  ('cpapir_cont1mag', 22250, 1),
  ('cpapir_cont1mag', 22260, 1),
  ('cpapir_cont1mag', 22270, 1),
  ('cpapir_cont1mag', 22280, 1),
  ('cpapir_cont1mag', 22290, 1),
  ('cpapir_cont1mag', 22300, 1),
  ('cpapir_cont1mag', 22310, 1),
  ('cpapir_cont1mag', 22320, 1),
  ('cpapir_cont1mag', 22330, 1),
  ('cpapir_cont1mag', 22340, 1),
  ('cpapir_cont1mag', 22350, 1),
  ('cpapir_cont1mag', 22360, 1),
  ('cpapir_cont1mag', 22370, 1),
  ('cpapir_cont1mag', 22380, 1),
  ('cpapir_cont1mag', 22390, 1),
  ('cpapir_cont1mag', 22400, 1),
  ('cpapir_cont1mag', 22410, 1),
  ('cpapir_cont1mag', 22420, 1),
  ('cpapir_cont1mag', 22430, 1),
  ('cpapir_cont1mag', 22440, 1),
  ('cpapir_cont1mag', 22450, 1),
  ('cpapir_cont1mag', 22460, 1),
  ('cpapir_cont1mag', 22470, 1),
  ('cpapir_cont1mag', 22480, 1),
  ('cpapir_cont1mag', 22490, 1),
  ('cpapir_cont1mag', 22500, 1),
  ('cpapir_cont1mag', 22510, 1),
  ('cpapir_cont1mag', 22520, 1),
  ('cpapir_cont1mag', 22530, 1),
  ('cpapir_cont1mag', 22540, 1),
  ('cpapir_cont1mag', 22550, 1),
  ('cpapir_cont1mag', 22560, 1),
  ('cpapir_cont1mag', 22570, 1),
  ('cpapir_cont1mag', 22580, 1),
  ('cpapir_cont1mag', 22590, 1),
  ('cpapir_cont1mag', 22600, 1),
  ('cpapir_cont1mag', 22610, 1),
  ('cpapir_cont1mag', 22620, 1),
  ('cpapir_cont1mag', 22630, 1),
  ('cpapir_cont1mag', 22640, 1),
  ('cpapir_cont1mag', 22650, 1),
  ('cpapir_cont1mag', 22660, 1),
  ('cpapir_cont1mag', 22670, 1),
  ('cpapir_cont1mag', 22680, 1),
  ('cpapir_cont1mag', 22690, 1),
  ('cpapir_cont1mag', 22700, 1),
  ('cpapir_cont1mag', 22710, 1),
  ('cpapir_cont1mag', 22720, 1),
  ('cpapir_cont1mag', 22730, 1),
  ('cpapir_cont1mag', 22740, 1),
  ('cpapir_cont1mag', 22750, 1),
  ('cpapir_cont1mag', 22760, 1),
  ('cpapir_cont1mag', 22770, 1),
  ('cpapir_cont1mag', 22780, 1),
  ('cpapir_cont1mag', 22790, 1),
  ('cpapir_cont1mag', 22800, 1),
  ('cpapir_cont1mag', 22810, 1),
  ('cpapir_cont1mag', 22820, 1),
  ('cpapir_cont1mag', 22830, 1),
  ('cpapir_cont1mag', 22840, 1),
  ('cpapir_cont1mag', 22850, 1),
  ('cpapir_cont1mag', 22860, 1),
  ('cpapir_cont1mag', 22870, 1),
  ('cpapir_cont1mag', 22880, 1),
  ('cpapir_cont1mag', 22890, 1),
  ('cpapir_cont1mag', 22900, 1),
  ('cpapir_cont1mag', 22910, 1),
  ('cpapir_cont1mag', 22920, 1),
  ('cpapir_cont1mag', 22930, 1),
  ('cpapir_cont1mag', 22940, 1),
  ('cpapir_cont1mag', 22950, 1),
  ('cpapir_cont1mag', 22960, 1),
  ('cpapir_cont1mag', 22970, 1),
  ('cpapir_cont1mag', 22980, 1),
  ('cpapir_cont1mag', 22990, 1),
  ('cpapir_cont1mag', 23000, 1),
  ('cpapir_cont1mag', 23010, 1),
  ('cpapir_cont1mag', 23020, 1),
  ('cpapir_cont1mag', 23030, 1),
  ('cpapir_cont1mag', 23040, 1),
  ('cpapir_cont1mag', 23050, 1);
INSERT INTO `data_photometric_bandpasses`
  (`moca_psid`, `wavelength_angstrom`, `relative_spectral_response`)
SELECT
  stage.`moca_psid`,
  stage.`wavelength_angstrom`,
  stage.`relative_spectral_response`
FROM `_mocaviz_cpapir_bandpass_stage` stage
WHERE NOT EXISTS (
  SELECT 1
  FROM `data_photometric_bandpasses` existing
  WHERE existing.`moca_psid` = 'cpapir_cont1mag'
  LIMIT 1
)
ORDER BY stage.`wavelength_angstrom`;
DELETE FROM `_mocaviz_cpapir_bandpass_stage`;

DROP TEMPORARY TABLE IF EXISTS `_mocaviz_cpapir_bandpass_stage`;
