#!/usr/bin/env python3
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


SOURCE_URL = "https://www.omm-astro.ca/en/for-observers/instruments-guide/"


@dataclass(frozen=True)
class CpapirFilter:
    moca_psid: str
    label: str
    center_um: float
    width_um: float

    @property
    def center_angstrom(self) -> float:
        return self.center_um * 10000.0

    @property
    def width_angstrom(self) -> float:
        return self.width_um * 10000.0

    @property
    def edge_min_angstrom(self) -> float:
        return (self.center_um - 0.5 * self.width_um) * 10000.0

    @property
    def edge_max_angstrom(self) -> float:
        return (self.center_um + 0.5 * self.width_um) * 10000.0

    @property
    def cdf05_angstrom(self) -> float:
        return (self.center_um - 0.45 * self.width_um) * 10000.0

    @property
    def cdf95_angstrom(self) -> float:
        return (self.center_um + 0.45 * self.width_um) * 10000.0


FILTERS = [
    CpapirFilter("cpapir_jmag", "J", 1.25, 0.16),
    CpapirFilter("cpapir_ch4mag", "CH4", 1.57, 0.05),
    CpapirFilter("cpapir_hmag", "H", 1.65, 0.30),
    CpapirFilter("cpapir_cont2mag", "CONT2", 2.033, 0.025),
    CpapirFilter("cpapir_heimag", "HeI", 2.062, 0.015),
    CpapirFilter("cpapir_civmag", "CIV", 2.081, 0.02),
    CpapirFilter("cpapir_kmag", "Ks", 2.15, 0.30),
    CpapirFilter("cpapir_brgammamag", "Brackett gamma", 2.165, 0.02),
    CpapirFilter("cpapir_heiimag", "HeII", 2.192, 0.04),
    CpapirFilter("cpapir_cont1mag", "CONT1", 2.255, 0.10),
]


def sql_string(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "''") + "'"


def sql_float(value: float) -> str:
    return f"{value:.12g}"


def top_hat_rows(filter_def: CpapirFilter, n: int = 101) -> list[tuple[float, float]]:
    start = filter_def.edge_min_angstrom
    stop = filter_def.edge_max_angstrom
    if n <= 1:
        return [(filter_def.center_angstrom, 1.0)]
    step = (stop - start) / (n - 1)
    return [(start + step * index, 1.0) for index in range(n)]


def build_sql() -> str:
    lines: list[str] = [
        "-- Review before applying to mocadb_private_tables.",
        "-- Generated by scripts/stage_cpapir_omm_bandpasses.py.",
        f"-- Source: {SOURCE_URL}",
        "-- OMM provides CPAPIR filter centers and widths, not measured transmission curves.",
        "-- Bandpass rows below are rectangular approximations over lambda +/- Delta_lambda/2.",
        "-- min_wavelength/max_wavelength are the 5%/95% CDF points of that rectangular approximation.",
        "-- Zeropoints are intentionally left unchanged.",
        "-- OMM also lists Pa beta and H2, but no matching CPAPIR moca_psid currently exists.",
        "-- cpapir_kmag is mapped to the OMM Ks entry.",
        "",
    ]
    for filter_def in FILTERS:
        psid = sql_string(filter_def.moca_psid)
        bandpass_file = sql_string(f"OMM CPAPIR rectangular approximation {filter_def.label}; {SOURCE_URL}")
        lines.extend([
            f"-- {filter_def.moca_psid}: {filter_def.label}, lambda={filter_def.center_um:g} um, Delta_lambda={filter_def.width_um:g} um",
            "SELECT",
            f"  {psid} AS `moca_psid`,",
            "  ps.`average_wavelength` AS `current_average_wavelength`,",
            f"  {sql_float(filter_def.center_angstrom)} AS `proposed_average_wavelength`,",
            "  ps.`min_wavelength` AS `current_min_wavelength`,",
            f"  {sql_float(filter_def.cdf05_angstrom)} AS `proposed_min_wavelength`,",
            "  ps.`max_wavelength` AS `current_max_wavelength`,",
            f"  {sql_float(filter_def.cdf95_angstrom)} AS `proposed_max_wavelength`,",
            "  ps.`zeropoint_jansky` AS `current_zeropoint_jansky`",
            "FROM `moca_photometry_systems` ps",
            f"WHERE ps.`moca_psid` = {psid};",
            "",
            "UPDATE `moca_photometry_systems`",
            "SET",
            f"  `average_wavelength` = COALESCE(`average_wavelength`, {sql_float(filter_def.center_angstrom)}),",
            f"  `min_wavelength` = COALESCE(`min_wavelength`, {sql_float(filter_def.cdf05_angstrom)}),",
            f"  `max_wavelength` = COALESCE(`max_wavelength`, {sql_float(filter_def.cdf95_angstrom)}),",
            f"  `bandpass_file` = COALESCE(`bandpass_file`, {bandpass_file})",
            f"WHERE `moca_psid` = {psid};",
            "",
            "CREATE TEMPORARY TABLE IF NOT EXISTS `_mocaviz_cpapir_bandpass_stage` (",
            "  `moca_psid` varchar(128) NOT NULL,",
            "  `wavelength_angstrom` double NOT NULL,",
            "  `relative_spectral_response` double NOT NULL",
            ") ENGINE=Memory;",
            "DELETE FROM `_mocaviz_cpapir_bandpass_stage`;",
            "INSERT INTO `_mocaviz_cpapir_bandpass_stage`",
            "  (`moca_psid`, `wavelength_angstrom`, `relative_spectral_response`)",
            "VALUES",
        ])
        values = [
            f"  ({psid}, {sql_float(wavelength)}, {sql_float(response)})"
            for wavelength, response in top_hat_rows(filter_def)
        ]
        lines.append(",\n".join(values) + ";")
        lines.extend([
            "INSERT INTO `data_photometric_bandpasses`",
            "  (`moca_psid`, `wavelength_angstrom`, `relative_spectral_response`)",
            "SELECT",
            "  stage.`moca_psid`,",
            "  stage.`wavelength_angstrom`,",
            "  stage.`relative_spectral_response`",
            "FROM `_mocaviz_cpapir_bandpass_stage` stage",
            "WHERE NOT EXISTS (",
            "  SELECT 1",
            "  FROM `data_photometric_bandpasses` existing",
            f"  WHERE existing.`moca_psid` = {psid}",
            "  LIMIT 1",
            ")",
            "ORDER BY stage.`wavelength_angstrom`;",
            "DELETE FROM `_mocaviz_cpapir_bandpass_stage`;",
            "",
        ])
    lines.append("DROP TEMPORARY TABLE IF EXISTS `_mocaviz_cpapir_bandpass_stage`;")
    return "\n".join(lines) + "\n"


def main() -> None:
    output = Path("bd_colors_fast/stage_omm_cpapir_bandpasses.sql")
    output.write_text(build_sql(), encoding="utf-8")
    print(output)


if __name__ == "__main__":
    main()
